language: node_js
node_js:
  - "node"
install:
  - npm install babel-cli babel-preset-es2015 babel-preset-react extend-tape gh-pages react-addons-test-utils react-scripts tape tape-jsx-equals faucet
script:
  - npm run test
