language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    
after_success:
  - git config --global user.name "vijayabharathi"
  - git config --global user.email "vijayabharathib@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://vijayabharathib:${GH_TOKEN}@github.com/vijayabharathib/fcc-project-react-recipies.git
  - npm run deploy
